name: Log Pull Request Information
on:
  issue_comment:
    types:
      - created
env:
  NODE_VERSION: "18"
jobs:
  run-happo:
    runs-on: ubuntu-latest
    steps:
      - name: Extract SHAs and URL from comment
        id: extract
        run: |
          echo "::set-output name=previous_sha::$(echo '${{ github.event.comment.body }}' | cut -d' ' -f3)"
          echo "::set-output name=current_sha::$(echo '${{ github.event.comment.body }}' | cut -d' ' -f4)"
          echo "::set-output name=change_url::$(echo '${{ github.event.comment.body }}' | cut -d' ' -f5)"
