name: Log Pull Request Information
on:
  issue_comment:
    types:
      - created
env:
  NODE_VERSION: "18"
jobs:
  run-happo:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Information
        id: extract-pr-info
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL)
          BASE_BRANCH=$(echo "$PR_INFO" | jq -r '.base.ref')
          LAST_COMMIT_SHA_BASE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$BASE_BRANCH" | jq -r '.sha')
          echo "LAST_COMMIT_SHA_BASE=${LAST_COMMIT_SHA_BASE}" >> $GITHUB_ENV
          LAST_COMMIT_SHA_HEAD=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL/commits | jq -r '.[-1].sha')
          echo "LAST_COMMIT_SHA_HEAD=${LAST_COMMIT_SHA_HEAD}" >> $GITHUB_ENV

          echo "BASE_BRANCH=${BASE_BRANCH}" >> $GITHUB_ENV
      - name: Log Pull Request Information
        run: |
          echo "Pull Request URL: ${{ github.event.issue.pull_request.html_url }}"
          echo "Last Commit SHA in Current Branch of PR: $LAST_COMMIT_SHA_HEAD"
          echo "Last Commit SHA in Base Branch of PR: $LAST_COMMIT_SHA_BASE"
          echo "Last Commit SHA in Base Branch of PR: $BASE_BRANCH"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.env.BASE_BRANCH }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
