name: Log Pull Request Information
on:
  issue_comment:
    types:
      - created
env:
  NODE_VERSION: "18"
jobs:
  run-happo:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Information
        id: pr_info
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL)

          BASE_BRANCH=$(echo "$PR_INFO" | jq -r '.base.ref')
          LAST_COMMIT_SHA_BASE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$BASE_BRANCH" | jq -r '.sha')
          echo "::set-output name=last_commit_sha_base::$LAST_COMMIT_SHA_BASE"

          LAST_COMMIT_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL/commits | jq -r '.[-1].sha')
          echo "::set-output name=last_commit_sha_head::$LAST_COMMIT_SHA"

      - name: Log Pull Request Information
        run: |
          echo "Pull Request URL: ${{ github.event.issue.pull_request.html_url }}"
          echo "Last Commit SHA in Current Branch of PR: ${{ steps.pr_info.outputs.last_commit_sha_head }}"
          echo "Last Commit SHA in Base Branch of PR: ${{ steps.pr_info.outputs.last_commit_sha_base }}"
