name: Log Pull Request Information
on:
  issue_comment:
    types:
      - created
env:
  NODE_VERSION: "18"
jobs:
  run-happo:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request information
        run: |
          PR_URL=$(echo "${{ github.event.comment.html_url }}" | sed 's/issue\/[0-9]*//g')
          echo "PR URL: $PR_URL"
          BASE_SHA=$(curl -s "$PR_URL.json" | jq -r '.pull_request.base.sha')
          HEAD_SHA=$(curl -s "$PR_URL.json" | jq -r '.pull_request.head.sha')
          echo "Base SHA: $BASE_SHA"
          echo "Head SHA: $HEAD_SHA"
