name: Log Pull Request Information
on:
  issue_comment:
    types:
      - created
env:
  NODE_VERSION: "18"
jobs:
  run-happo:
    runs-on: ubuntu-latest
    steps:
      - name: Extract SHAs and URL from comment
        id: extract
        run: |
          echo "::set-output name=previous_sha::$(echo '${{ github.event.comment.body }}' | cut -d' ' -f3)"
          echo "::set-output name=current_sha::$(echo '${{ github.event.comment.body }}' | cut -d' ' -f4)"
          echo "::set-output name=change_url::$(echo '${{ github.event.comment.body }}' | cut -d' ' -f5)"
      - name: Log Pull Request Information
        run: |
          echo "Pull Request URL: ${{ steps.extract.outputs.change_url }}"
          echo "Pull Request URL2: ${{ github.event.issue.pull_request.html_url }}"
          echo "Pull Request URL3: ${{ github.event.comment.issue_url }}"
          echo "Head SHA: ${{ steps.extract.outputs.current_sha }}"
          echo "Base SHA: ${{ steps.extract.outputs.previous_sha }}"
