name: Log Pull Request Information
on:
  issue_comment:
    types:
      - created
env:
  NODE_VERSION: "18"
jobs:
  run-happo:
    runs-on: ubuntu-latest
    steps:
      - name: Extract SHAs and URL from comment
        id: last_commit_sha
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          LAST_COMMIT_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL/commits | jq -r '.[-1].sha')
          echo "::set-output name=last_commit_sha::$LAST_COMMIT_SHA"

      - name: Log Pull Request Information
        run: |
          echo "Pull Request URL: ${{ github.event.issue.pull_request.html_url }}"
          echo "Head SHA (last commit sha in current branch of PR): ${{ steps.last_commit_sha.outputs.last_commit_sha  }}"
