name: Pull Request Workflow from v23.x

on:
  pull_request:
    branches:
      - master #current latest version
      - "v[1-9][0-9]+.x" #release branches with previous releases
      - "v[1-9][0-9]+-next" #next release branches
# + feat -> master
# + feat -> v24.x
# + feat -> v25-next
# - feat1 -> feat2

jobs:
  test-job:
    name: "Test job"
    runs-on: "ubuntu-latest"
    steps:
      - name: Test step
        run: echo 'Run test step'
      - uses: actions/checkout@v3
