name: Pull Request Workflow from v23.x

on:
  pull_request:

# + feat -> master
# + feat -> v24.x
# + feat -> v25-next
# - feat1 -> feat2

jobs:
  test-job:
    name: "Test job"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check if base branch is valid
        run: |
          base_branch="${{ github.event.pull_request.base.ref }}"
          if [[ $base_branch == "master" || $base_branch =~ ^v[1-9][0-9]+\.x$ || $base_branch =~ ^v[1-9][0-9]+-next$ ]]; then
            echo "Base branch is valid: $base_branch"
          else
            echo "Error: Base branch '$base_branch' is not valid"
            exit 1
          fi
      - name: Test step
        run: echo 'Run test step'
      - uses: actions/checkout@v3
